### ISSUE TITLE
Compilation error:Duplicate class org.openudid.OpenUDID_manager found in modules jetified-idnow-platform-4.6.0-runtime.jar (de.idnow.android.sdk:idnow-platform:4.6.0) and jetified-sdk-20.04.2-runtime.jar (ly.count.android:sdk:20.04.2)

### ISSUE THREAD

**Issue by Kwazir** [idnow/de.idnow.android.sdk#39]
I'm using 4.6.0 SDK. this SDK with latest version of the other idnow's library (de.idnow.android, version 4.5.1) even does not compile.

Compilation ends with the result:
```
Duplicate class org.openudid.OpenUDID_manager found in modules jetified-idnow-platform-4.6.0-runtime.jar (de.idnow.android.sdk:idnow-platform:4.6.0) and jetified-sdk-20.04.2-runtime.jar (ly.count.android:sdk:20.04.2)
Duplicate class org.openudid.OpenUDID_manager$1 found in modules jetified-idnow-platform-4.6.0-runtime.jar (de.idnow.android.sdk:idnow-platform:4.6.0) and jetified-sdk-20.04.2-runtime.jar (ly.count.android:sdk:20.04.2)
Duplicate class org.openudid.OpenUDID_manager$ValueComparator found in modules jetified-idnow-platform-4.6.0-runtime.jar (de.idnow.android.sdk:idnow-platform:4.6.0) and jetified-sdk-20.04.2-runtime.jar (ly.count.android:sdk:20.04.2)
Duplicate class org.openudid.OpenUDID_service found in modules jetified-idnow-platform-4.6.0-runtime.jar (de.idnow.android.sdk:idnow-platform:4.6.0) and jetified-sdk-20.04.2-runtime.jar (ly.count.android:sdk:20.04.2)
Duplicate class org.openudid.OpenUDID_service$1 found in modules jetified-idnow-platform-4.6.0-runtime.jar (de.idnow.android.sdk:idnow-platform:4.6.0) and jetified-sdk-20.04.2-runtime.jar (ly.count.android:sdk:20.04.2)
```

**Comment by linhnguyen-idnow** [comment]
@Kwazir Were your HostApp using Android Support or Androidx Library?

**Comment by Kwazir** [comment]
@linhnguyen-idnow yes, I'm using Jetpack AndroidX Libraries.
Described problem appeared after upgrading "de.idnow.android" from version 4.5.0 to 4.5.1

**Comment by Kwazir** [comment]
@linhnguyen-idnow
Something has changed in the matter of this issue?

**Comment by linhnguyen-idnow** [comment]
@Kwazir could you please share your sample project to me? I would like to check directly on that

**Comment by rfejer-idnow** [comment]
Hi @Kwazir 

We checked with both of our SDKs and could reproduce this issue under certain circumstances. The fix will be included in the next release of the VideoIdent SDK: https://github.com/idnow/de.idnow.android

Thanks for your patience,
Robert

**Comment by For3ster** [comment]
I have the same issue as well. So, will be waiting for the update

**Comment by For3ster** [comment]
Now the similar issue is reproducing with updated versions of idnow sdk (autoident 4.7.0 and videoident 5.0.1) but with different classes: `Duplicate class de.idnow.insights.*`

**Comment by Kwazir** [comment]
The problem has been solved with autoident 4.7.0 /  videoident 4.5.1

**Comment by For3ster** [comment]
Duplication of `de.idnow.insights.*` is still actual for videoident 5.0.2. Please, fix this issue as it's impossible to build the project using the latest versions of your libraries.

**Comment by For3ster** [comment]
@rfejer-idnow @linhnguyen-idnow @souheib93 the problem is still relevant with the latest version

**Comment by rfejer-idnow** [comment]
This is fixed with VideoIdent 5.0.7 and AutoIdent 4.8.1.

**Comment by For3ster** [comment]
Yes, it works with videoident 5.0.6 as well
